### ISSUE TITLE
404 Status

### ISSUE THREAD

**Issue by travisdock** [ericandrewlewis/mta-realtime-subway-departures#3]
I ran these commands:
```
npx create-react-app my-app
cd my-app
npm install --save mta-realtime-subway-departures
```

I then copied and pasted the usage example from the ReadMe into my app.js:
```
const { createClient } = require('mta-realtime-subway-departures');

// Get your API key at http://datamine.mta.info/user
const MTA_API_KEY = 'Your-API-Key-Here';
const client = createClient(MTA_API_KEY);

client.departures(625)
  .then((response) => {
    console.log(response);
  });

// Also accepts an array of complex IDs.
client.departures([625, 232])
  .then((responses) => {
    // Responses is an array of response objects.
    console.log(responses);
  });

```
I then got the following errors (I disconnected dev server before taking the screenshot so ignore the last line)

![image](https://user-images.githubusercontent.com/36681963/42825260-9faaaf2e-89af-11e8-8d20-778a03c46ff8.png)

I believe it is coming from this line:
`const transit = protobuf.loadProtoFile( path.join(__dirname, 'nyct-subway.proto'),);`

Any thoughts on why this is happening?

**Comment by ebfg** [comment]
I was able to get it working by copying `nyct-subway.proto` and `gtfs-realtime.proto` into `public/`. I did have to change `import "gtfs-realtime.proto";` in `nyct-subway.proto` to `import "localhost:3000/gtfs-realtime.proto";`

**Comment by travisdock** [comment]
Great, thanks!
