### ISSUE TITLE
1.1.0-beta

### ISSUE THREAD

**Issue by ericandrewlewis** [ericandrewlewis/mta-realtime-subway-departures#9]
I'm making a [1.1.0-beta release](https://github.com/ericandrewlewis/mta-realtime-subway-departures/releases/tag/1.1.0-beta) available for testing in your projects.

If you'd like to test, try installing it in your project:

```
npm install https://github.com/ericandrewlewis/mta-realtime-subway-departures.git#1.1.0-beta
```

Please comment on this issue if you have any problems with it.

Hearing no issues, I'll publish this to `latest` on npm next Tuesday, October 6th.

1.1.0 is a maintenance release. It includes dependency updates, some of which were of "critical" level npm.

**Comment by Elaniobro** [comment]
@ericandrewlewis initial testing of the beta release in my application yielded zero bugs/issues. Looks good to me!

**Comment by ericandrewlewis** [comment]
1.1.0 is now [on npm](https://www.npmjs.com/package/mta-realtime-subway-departures/v/1.1.0)
